### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by guifou** [Ziqi-Li/geoshapley#9]
Hi @Ziqi-Li 

I try to use your package to solve a  classification problem, but when I use the following code, I get the error:

background_X = X_coords.sample(10).values
explainer = GeoShapleyExplainer(rf_model.predict, background_X)
rslt = explainer.explain(X_coords,n_jobs=-1)

**numpy.core._exceptions.MemoryError: Unable to allocate 5.38 PiB for an array with shape (8796093022208, 86) and data type float64**

In my case, X_coords has the size [20 rows x 42 columns]. I really don't know how to solve this problem.

Thanks for helping.

**Comment by Ziqi-Li** [comment]
@guifou Hi, yes, it is because there are too many features. The current implementation would be challenging for more than, say 15 features, depending on your device specs. It is less sensitive to the number of observation though. I suggest to perform feature selection first before geoshapley explanations.
